import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign in - Movie App",
  description: "Generated by create next app",
};

export default function SignInLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return <>{children}</>;
}
