import type { Metadata } from "next";
import MainHeader from "@/components/share/main-header";
import AuthGuard from "@/components/share/auth-guard";
import Container from "@/components/ui/container";

export const metadata: Metadata = {
  title: "Home - Movie App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthGuard>
      <MainHeader isTransparent={false} isShowBar={true} />
      <Container>
        {children}
      </Container>
    </AuthGuard>
  );
}
