import type { Metadata } from "next";
import AccountNavbar from "@/features/user/accountNavbar";

export const metadata: Metadata = {
  title: "Account - Movie App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <AccountNavbar className="mr-10" />
      {children}
    </div>
  );
}
