import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Account - Movie App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="flex">
    <div>
      <p>Hello</p>
    </div>
    {children}
  </div>;
}
